pipeline {
    agent any

    stages {
        stage('Clonar') {
            steps {
                git 'https://github.com/ElkinContrerasR/mi-app.git'
            }
        }
        stage('Compilar') {
            steps {
                sh './mvnw clean package -DskipTests'
            }
        }
        stage('Docker Build') {
            steps {
                sh 'docker build -t miapp .'
            }
        }
        stage('Desplegar') {
            steps {
                sh 'docker compose down'
                sh 'docker compose up -d --build'
            }
        }
    }
}
