pipeline {
    agent any

    stages {
        stage('Clonar') {
            steps {
                git branch: 'main', url: 'https://github.com/ElkinContrerasR/mi-app.git'
            }
        }
        stage('Compilar') {
            steps {
                dir('demo') {
            // Asegúrate de que mvnw tenga permisos de ejecución
            sh 'chmod +x mvnw'
            sh './mvnw clean package -DskipTests'
        }
            }
        }
        stage('Docker Build') {
            steps {
                sh 'docker build -t miapp demo/.'
            }
        }
        stage('Desplegar') {
            steps {
                sh 'docker compose down'
                sh 'docker compose up -d --build'
            }
        }
    }
}
